version: "3.9"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  base-geth:
    restart: "unless-stopped"
    build:
      context: ./base-geth
      dockerfile: Dockerfile.binary
      args:
        - DOCKER_TAG=${BASEGETH_DOCKER_TAG}
    image: base-geth:local
    stop_grace_period: 5m
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - EL_EXTRAS=${EL_EXTRAS}
    volumes:
      - basegeth-data:/var/lib/base-geth
      - jwtsecret:/var/lib/base-geth/ee-secret
      - ./${NETWORK}:/tmp/network:ro
      - /etc/localtime:/etc/localtime:ro
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - geth
      - --op-network
      - base-${NETWORK}
      - --datadir
      - /var/lib/base-geth
      - --rollup.sequencerhttp
      - ${SEQUENCER}
      - --rollup.disabletxpoolgossip
      - --authrpc.addr
      - 0.0.0.0
      - --authrpc.port
      - "8551"
      - --authrpc.jwtsecret
      - /var/lib/base-geth/ee-secret/jwtsecret
      - --authrpc.vhosts=*
      - --http
      - --http.addr
      - 0.0.0.0
      - --http.port
      - ${RPC_PORT:-8545} 
      - --http.vhosts=*
      - --http.corsdomain=*
      - --ws
      - --ws.addr
      - 0.0.0.0
      - --ws.port
      - ${WS_PORT:-8546}
      - --ws.origins=*
      - --metrics
      - --metrics.expensive
      - --pprof
      - --pprof.addr
      - 0.0.0.0
      - --syncmode
      - full
      - --maxpeers
      - "0"
      - --nodiscover
    labels:
      - traefik.enable=true
      - traefik.http.routers.${RPC_HOST:-base}.service=${RPC_HOST:-base}
      - traefik.http.routers.${RPC_HOST:-base}.entrypoints=websecure
      - traefik.http.routers.${RPC_HOST:-base}.rule=Host(`${RPC_HOST:-base}.${DOMAIN}`)
      - traefik.http.routers.${RPC_HOST:-base}.tls.certresolver=letsencrypt
      - traefik.http.routers.${RPC_HOST:-base}lb.service=${RPC_HOST:-base}
      - traefik.http.routers.${RPC_HOST:-base}lb.entrypoints=websecure
      - traefik.http.routers.${RPC_HOST:-base}lb.rule=Host(`${RPC_LB:-base-lb}.${DOMAIN}`)
      - traefik.http.routers.${RPC_HOST:-base}lb.tls.certresolver=letsencrypt
      - traefik.http.services.${RPC_HOST:-base}.loadbalancer.server.port=${RPC_PORT:-8545}
      - traefik.http.routers.${WS_HOST:-basews}.service=${WS_HOST:-basews}
      - traefik.http.routers.${WS_HOST:-basews}.entrypoints=websecure
      - traefik.http.routers.${WS_HOST:-basews}.rule=Host(`${WS_HOST:-basews}.${DOMAIN}`)
      - traefik.http.routers.${WS_HOST:-basews}.tls.certresolver=letsencrypt
      - traefik.http.routers.${WS_HOST:-basews}lb.service=${WS_HOST:-basews}
      - traefik.http.routers.${WS_HOST:-basews}lb.entrypoints=websecure
      - traefik.http.routers.${WS_HOST:-basews}lb.rule=Host(`${WS_LB:-basews-lb}.${DOMAIN}`)
      - traefik.http.routers.${WS_HOST:-basews}lb.tls.certresolver=letsencrypt
      - traefik.http.services.${WS_HOST:-basews}.loadbalancer.server.port=${WS_PORT:-8546}
      - metrics.scrape=true
      - metrics.path=/debug/metrics/prometheus
      - metrics.port=6060

  base-node:
    restart: "unless-stopped"
    build:
      context: ./base-node
      dockerfile: Dockerfile.binary
      args:
        - DOCKER_TAG=${BASENODE_DOCKER_TAG}
    image: base-node:local
    stop_grace_period: 5m
    environment:
      - CL_EXTRAS=${CL_EXTRAS}
      - OP_NODE_P2P_AGENT=base
    volumes:
      - jwtsecret:/var/lib/base-node/ee-secret
      - ./${NETWORK}:/tmp/network:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${BASENODE_P2P_PORT:-9222}:${BASENODE_P2P_PORT:-9222}/tcp
      - ${BASENODE_P2P_PORT:-9222}:${BASENODE_P2P_PORT:-9222}/udp
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - op-node
      - --log.level
      - ${LOG_LEVEL}
      - --l2
      - ${L2_CONNECTION_KIND:-http}://base-geth:8551
      - --l2.jwt-secret
      - /var/lib/base-node/ee-secret/jwtsecret
      - --rollup.config
      - /tmp/network/rollup.json
      - --l1
      - ${L1_RPC}
      - --l1.rpckind
      - ${L1_RPC_KIND:-basic}
      - --rpc.addr
      - 0.0.0.0
      - --rpc.port
      - "9545" 
      - --metrics.enabled
      - --p2p.listen.tcp
      - ${BASENODE_P2P_PORT:-9222}
      - --p2p.bootnodes
      - ${BASENODE_P2P_BOOTNODES}
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=7300

  set-prune-marker:
    profiles: ["tools"]
    image: alpine:3
    restart: "no"
    volumes:
      - basegeth-data:/var/lib/base-geth
    entrypoint: ["/bin/sh","-c"]
    command: /bin/sh

volumes:
  basegeth-data:
  jwtsecret:
